### ISSUE TITLE
Win10自带hyper-v虚拟机引导ISO启动镜像启动失败

### ISSUE THREAD

**Issue by hetykai** [openthos/openthos#12]
![vmconnect_2018-03-27_12-03-58](https://user-images.githubusercontent.com/3378432/37946312-59e17aae-31b7-11e8-859a-db6b97d7cae9.png)

**Comment by Lesita** [comment]
查看虚拟电脑的“世代”。第 2 代只允许 EFI 固件的光盘启动。

这种问题和这个操作系统没有任何关系，请不要麻烦别人。

________________________________

**Comment by cwhuang** [comment]
Of course OPENTHOS supports to boot from UEFI.

Which ISO did you use exactly?

**Comment by hetykai** [comment]
抱歉麻烦到你。但是hyper-v是支持uefi启动的，我已经设置了从UEFI引导，却引导不成功，所以才反馈的。
我用的 [http://pan.baidu.com/s/1kVauJ5t](http://pan.baidu.com/s/1kVauJ5t) PassWord: y48g
openthos20180322/eng/openthos-1.0.0.180322-eng.iso


I used [http://pan.baidu.com/s/1kVauJ5t](http://pan.baidu.com/s/1kVauJ5t) PassWord: y48g
openthos20180322/eng/openthos-1.0.0.180322-eng.iso

I have set UEFI boot in hyper-v, but it cannot boot

**Comment by faxiang1230** [comment]
I think you use the wrong image,please try *_oto.img,If you can't get it,email to OPENTHOS.
Ref:https://github.com/openthos/oto_bootable_newinstaller/blob/multiwindow/Android.mk
thanks.

**Comment by hetykai** [comment]
Ok, thanks.
