### ISSUE TITLE
upload the file on other server please 

### ISSUE THREAD

**Issue by msh2050** [openthos/openthos#13]
it is very difficult to download from baidu
please at least provide monthly update link on release section of github

**Comment by yeungtuzi** [comment]
New server cluster are planned to be online these weeks, hope this will help a lot. It will have a dedicated 100Mbps connection.

发自我的 iPhone

**Comment by yeungtuzi** [comment]
Hi there,
Before our server cluster get online this week, I just upload a preview
build of openthos 2.0 at microsoft onedrive:
https://1drv.ms/f/s!AlYwncDPcD8SgaoNXKFSw5ieqCk9oQ
please use ultraiso(commercial software with free trial) to burn this image
file to a USB disk (4GB or larger) then boot with that USB disk and follow
the instructions.
Cheers.

msh2050 <notifications@github.com> 于2018年8月25日周六 上午12:16写道：

**Comment by Neurovert** [comment]
Why not use official release spaces like Fosshub? 
https://www.fosshub.com/OPENTHOS.html
