### ISSUE TITLE
Daily Report 2016-04-07 LuoHao

### ISSUE THREAD

**Issue by ladehunter** [openthos/openthos#4]
1.在董鹏的协助下完成了点击startmenu的apk图标后startmenu会消失的实现。

2.完成在startmenu出现的情况下再次点击start键startmenu会消失的实现。

3.考察了android点击接收，初步规划了点击任何地方startmenu都会消失的实现方法。

**Comment by chyyuu** [comment]
请把你的日报告放到multiwin-analysis的issues中
